# SPDX-License-Identifier: EPICS
# Helmholtz-Zentrum Berlin fuer Materialien und Energie GmbH 2023-2024
# Lutz Rossa <rossa@helmholtz-berlin.de>

TOP = ..
include $(TOP)/configure/CONFIG
DIRS += $(wildcard *ioc*)
DIRS += $(wildcard as*)
include $(CONFIG)/RULES_DIRS

